project:
  type: website
  output-dir: docs
  resources:
    - "assets"

website:
  title: "Imago training"

  page-footer:
    center: |
      [[Imago]{.green}](https://imago.ac.uk), part of the [[Smart Data Research UK]{.blue}](https://www.sdruk.ukri.org/) family.

  favicon: assets/Imago-logo.png
  repo-url: https://github.com/Imago-SDRUK/Imago-training
  repo-branch: main
  repo-actions: [edit, issue]

  search:
    location: sidebar
    type: overlay

  sidebar:
    style: floating
    collapse-level: 1
    logo: assets/Imago-logo.png
    tools:
      - icon: github
        href: https://github.com/Imago-SDRUK/Imago-training
    contents:
      - index.qmd
      - section: "Getting oriented"
        contents:
          - datasets.qmd
          - satellites_to_areas.qmd
      - section: "1. Policy trainings"
        contents:
          - policy.qmd
      - section: "2. Research trainings"
        contents:
          - section: "Air temperature"
            contents:
              - airtemp_1.qmd
              - airtemp_2.qmd
              - airtemp_3.qmd
              - airtemp_4.qmd
          - section: "Precipitation"
            contents:
              - precipitation_1.qmd
              - precipitation_2.qmd
              - precipitation_3.qmd
          - spf.qmd
      - section: "Reference"
        contents:
          - packages.qmd
      - text: "---"
      - text: "Imago"
        href: https://imago.ac.uk
      - text: "GDSL"
        href: https://liverpool.ac.uk/geographic-data-science

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - assets/imago.scss
    include-in-header:
      - text: |
          <script defer src="https://events.imago.ac.uk/script.js" data-website-id="REPLACE_WITH_TRAINING_SITE_ID"></script>

editor: visual
